#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit 1

readarray -t ABOUT << "EOF"
Having Bad Luck? Touched by Evil Hands? Need help in Love, Luck, & Money, etc.?
CWJ can help with a reading from the Red Devil Dream Book
EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done
